---
name: publish ayushnix wiki

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout the mkdocs repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      - name: upgrade pip, install mkdocs material, and some extensions
        run: >-
          python -m pip install --upgrade pip mkdocs-material
          mkdocs-git-revision-date-localized-plugin
      - name: deploy mkdocs in gh-pages
        run: mkdocs gh-deploy --force
